### PR TITLE
fixes for package and module imports

### PR DESCRIPTION
**Pull request by chase-moskal**
see each commit for more details

### CODE REVIEW

**Comment by chase-moskal** [comment]
i closed this, but it was actually correctly done in the first place.. reopening...

**Comment by zenkyuv** [comment]
hello is this here where I review your code xd ?

**Comment by zenkyuv** [comment]
> see each commit for more details
im just learnig github comments (●'◡'●)

**Comment by chase-moskal** [comment]
@zenkyuv — yep, you're getting it!

this is how most collaboration happens on github. devs submit pull requests like this one, to each other, and the maintainers of the project will review the commits in the pull request.

when you're ready, you can merge these changes

**Pull request merged**
